server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #   active: native
  cloud:
    config:
      server:
#       native:
#        search-locations: "classpath:/config"
#        search-locations: "file:///Users/phucnguyen/udemy_Microservice_EazyBytes/practiceCode/config"
         git:
           uri: "https://github.com/phucgigital03/Bank-configserver.git"
           default-label: main
           timeout: 5
           clone-on-start: true
           force-pull: true

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9" # In production, use a secure key management system run with CLI argument

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
